# -*- coding: utf-8 -*-
"""FoP oyun kodu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TgifudSXXXXfftzqe690lFcIH1wAVJ96
"""

#@title answer
answer = "This is a super fun game."

import string
alphabet = list(string.ascii_lowercase)
print(alphabet)

pip install colorama

from colorama import Fore, Style, init
init(autoreset=True)

from IPython.display import display, HTML

def generate_feedback(answer, guessed_letters):
  """
  Generates a partially revealed version of the answer based on guessed letters.
  """
  result = ""
  for ch in answer:
    if ch == ' ':
      result += '  '
    elif ch == '.':
      result += '.'
    elif ch.lower() in guessed_letters:
      result += ch
    else:
      result += '_ '
  return result

#Hide the letters in the sentence, e.g. "I have a cat." becomes "_  _ _ _ _  _  _ _ _."

def hide_letters(sentence):
  """
  Returns a version of the input sentence with all letters hidden.
  Letters are replaced with underscores followed by a space ("_ ").
  Spaces between words are preserved as double spaces ("  ") for visual clarity.
  """
  result = ""
  for a in sentence:
    if a == ' ':
      result += '  '
    elif a == '.':
      result += '.'
    else:
      result += '_ '
  return result

#Currently only works with "." punctuation, add others (maybe with RegEx?)

def FoP(answer):
  attempts = 15
  import string
  guessed_letters = set()

  answer_tokenized = answer.replace(".", "").lower().split(" ")
  answer_lower = answer.lower()
  correct_letters = set(ch for ch in answer_lower if ch in string.ascii_lowercase)
  feedback = hide_letters(answer)
  print(f"Welcome to Forage of Phrases!\nHow to play:\n 1. Guess a word.\n 2. If the word is in the sentence, its letters are revealed.\n 3. If not, you can still see which letters of your word is still in the sentence.\nHave fun!")
  print(f"\nThe secret phrase is: {feedback}\n")

  def keyboard_display(guessed_letters, correct_letters):
    rows = ["qwertyuiop", "asdfghjkl", "zxcvbnm"]
    html = ""
    for row in rows:
      for letter in row:
        if letter in guessed_letters:
          if letter in correct_letters:
            color = "white"
            bg = "green"
          else:
            color = "white"
            bg = "gray"
        else:
          color = "black"
          bg = "transparent"
        html += f'<span style="color: {color}; background-color: {bg}; padding: 2px 5px; margin:1px; border-radius:3px;">{letter.upper()}</span>'
      html += '<br>'
    display(HTML(html))

  for x in range(attempts):
    print(f"Attempt {x + 1} of {attempts}\n")
    guess = input("Guess a word: ").strip().lower()

    if guess not in word_list:
      print("Please enter a valid word.")

    elif guess in answer_tokenized:
      guessed_letters.update(guess)
      feedback = generate_feedback(answer, guessed_letters)
      print(f"\nYour word is in the sentence :)\n\nThe secret phrase is: {feedback}\n")
    else:
      guessed_letters.update(guess)
      for i in guess:
        if i in answer_lower:
          correct_letters.add(i)
      print(f"\nYour word is not in the sentence :(\n\nThe secret phrase is: {feedback}\n")
    keyboard_display(guessed_letters, correct_letters)

    if '_' not in feedback:
      print("Congrats! \nYou have successfully foraged the phrase!\n:))")
      break

FoP(answer)